[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  publish = "build"
  port = 5173
  targetPort = 8082
  framework = "#custom"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

