[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 5173
  targetPort = 8082
  framework = "#custom"

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com https://rsms.me https://api.netlify.com; script-src-elem 'self' https://in.getclicky.com https://static.getclicky.com; style-src 'self' https://fonts.googleapis.com https://rsms.me 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://static.getclicky.com; worker-src 'self' blob: "
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

